FROM python:alpine
ARG python:alpine AS build

FROM python:alpine AS BUILD
ENV python:alpine AS build

FrOm --platform=$BUILDPLATFORM python:alpine@sha256:0135ae6442d1269379860b361760ad2cf6ab7c403d21935a8015b48d5bf78a86 As build-deps
