---
name: build

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install Poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install -v
      - name: Cache pre-commit hooks
        id: cache-pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: pre-commit-
      - name: Prune pre-commit hooks
        if: steps.cache-pre-commit.outputs.cache-hit != 'true'
        run: poetry run pre-commit gc
      - name: Run gitlint
        run: poetry run pre-commit run --color=always --hook-stage manual gitlint-ci
      - name: Run pre-commit
        if: success() || failure()
        run: poetry run pre-commit run --all-files --color=always --show-diff-on-failure

  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run super-linter
        uses: github/super-linter@v4.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_MARKDOWN: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_YAML: false

  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pipx install --python '${{ steps.setup-python.outputs.python-path }}' poetry
      - name: Install dependencies
        run: poetry install --only=main,test -v
      - name: Run pytest
        run: poetry run pytest --color=yes --cov-report=term --cov-report=xml --with-functional
      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.2
      - name: Run SonarCloud scanner
        uses: SonarSource/sonarcloud-github-action@v1.9
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release:
    if: github.ref == 'refs/heads/master'
    needs: [pre-commit, super-linter, pytest]
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Python Semantic Release
        uses: relekang/python-semantic-release@v7.33.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
