---
name: release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@v7.23.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: ${{ secrets.PYPI_USERNAME }}
          repository_password: ${{ secrets.PYPI_PASSWORD }}
