---
name: test

on: [push, pull_request]

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.4
      - name: Install dependencies
        run: |
          poetry install --ansi -v
      - name: Set up Docker
        if: matrix.os == 'macos-latest'
        run: |
          # https://github.com/docker/for-mac/issues/2359#issuecomment-943131345
          brew install --cask docker
          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
          open -a /Applications/Docker.app --args --unattended --accept-license
          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
      - name: Run pytest
        run: |
          poetry run pytest --color=yes --cov-report=term --cov-report=xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v2.1.0
